
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjgfdmyauopdoxumvqxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZ2ZkbXlhdW9wZG94dW12cXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDYzNjYsImV4cCI6MjA2MjY4MjM2Nn0.r2rw2USkNlFLFoZtqDJuyRWRmtCrzq1WVVB7_0fJxtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
